// ============================================================================
//  ASSET SLOTS — every imported model the game knows how to use.
//  Files live under /assets (see assets/README.md for modelling specs).
//  A slot whose file is missing simply falls back to the procedural prototype model.
//  `assets/manifest.json` (generated by `npm run assets`) lists the files that exist,
//  so missing optional files are never requested (no 404s).
// ============================================================================

export const ASSET_ROOT = 'assets/';

/** sneaker id → assets/sneakers/<file>.glb  (one RIGHT shoe; the left foot is mirrored automatically) */
export const SNEAKER_FILES = {
  starter: 'starter_canvas', street: 'street_runner', retro: 'retro_high', court: 'court_classic',
  dunk: 'urban_dunk', airsprint: 'air_sprint', velocity: 'velocity_x', neon: 'neon_runner',
  carbon: 'carbon_racer', hyper: 'hyper_boost', plasma: 'plasma_kicks', cosmic: 'cosmic_runner',
  galaxy: 'galaxy_high', quantum: 'quantum_sneakers',
};

/** Normalisation applied to every sneaker file (authors don't need exact scale/origin). */
export const SNEAKER_SPEC = {
  length: 0.31,     // metres heel→toe after auto-fit (the character's foot socket is sized for this)
  ankleU: 0.27,     // origin is placed under the ankle, 27% of the length from the heel
};

/** pet species → assets/pets/<file>.glb. Pets share species models; finishes (golden, neon…) are material variants. */
export const PET_FILES = {
  dog: 'dog', cat: 'cat', bunny: 'bunny', bird: 'pigeon', fox: 'fox', robodog: 'robot_dog',
  tiger: 'tiger', dragon: 'dragon', unicorn: 'unicorn', phoenix: 'phoenix', bear: 'bear', slime: 'slime',
};
export const PET_SPEC = { height: 0.72 };

/** Rigged player character. Clip names are matched case-insensitively against these aliases. */
export const CHARACTER = {
  file: 'characters/runner.glb',
  height: 1.8,
  clips: {
    idle: ['idle', 'breathing idle', 'stand'],
    walk: ['walk', 'walking'],
    run: ['run', 'running', 'jog'],
    sprint: ['sprint', 'fast run', 'run_fast'],
    celebrate: ['celebrate', 'victory', 'cheer', 'dance', 'wave'],
    jump: ['jump', 'jumping', 'fall'],
    stumble: ['stumble', 'hit', 'trip'],
  },
  // native ground speed (m/s) of each locomotion clip at timeScale 1 for a 1.8 m character
  clipSpeeds: { walk: 1.6, run: 3.9, sprint: 6.5 },
  // switch thresholds (m/s)
  walkUntil: 2.6,
  runUntil: 7.5,
  stepPhases: [0.0, 0.5],   // normalised clip times where a foot plants (footstep sounds)
  footBones: {
    left: ['foot_l', 'foot.l', 'leftfoot', 'mixamorigleftfoot', 'mixamorig:leftfoot', 'def-foot.l', 'l_foot', 'foot_left'],
    right: ['foot_r', 'foot.r', 'rightfoot', 'mixamorigrightfoot', 'mixamorig:rightfoot', 'def-foot.r', 'r_foot', 'foot_right'],
  },
  hipsBones: ['hips', 'mixamorighips', 'mixamorig:hips', 'pelvis', 'root'],
  hideMeshes: ['shoe', 'shoes', 'sneaker', 'footwear'], // the character's own shoes are hidden; game sneakers attach to the feet
  shoeScale: 1.12,
};

/** Lobby props → assets/props/<file>.glb, auto-fitted to these sizes (metres). */
export const PROPS = {
  tree:  { file: 'props/tree.glb',  fit: { height: 5.2 } },
  bench: { file: 'props/bench.glb', fit: { length: 2.6 } },
  lamp:  { file: 'props/lamp.glb',  fit: { height: 5.4 } },
};

/** Future slots (documented now, wired in later migration steps). */
export const FUTURE_SLOTS = [
  'environment/sneaker_shop.glb', 'environment/pet_hatchery.glb', 'environment/run_portal.glb',
  'environment/building_a.glb', 'environment/building_b.glb', 'environment/building_c.glb',
  'props/display_shelf.glb', 'props/display_pedestal.glb', 'props/planter.glb', 'props/bollard.glb',
  'props/neon_sign.glb', 'props/track_hurdle.glb', 'props/traffic_barrier.glb', 'props/egg.glb',
];

/** Per-file tuning without re-exporting (rotate a model that faces the wrong way, nudge sockets…). */
export const ASSET_OVERRIDES = {
  // 'sneakers/starter_canvas.glb': { rotateY: 90 },
  // 'characters/runner.glb': { clipSpeeds: { run: 4.2 }, shoeScale: 1.05, socketOffset: [0, 0, 0.02] },
};
