// ============================================================================
//  ASSET SLOTS — every imported model the game knows how to use.
//  Files live under /assets (see assets/README.md for modelling specs).
//  A slot whose file is missing simply falls back to the procedural prototype model.
//  `assets/manifest.json` (generated by `npm run assets`) lists the files that exist,
//  so missing optional files are never requested (no 404s).
// ============================================================================

export const ASSET_ROOT = 'assets/';

/** sneaker id → assets/sneakers/<file>.glb  (one RIGHT shoe; the left foot is mirrored automatically) */
export const SNEAKER_FILES = {
  starter: 'starter_canvas', street: 'street_runner', retro: 'retro_high', court: 'court_classic',
  dunk: 'urban_dunk', airsprint: 'air_sprint', velocity: 'velocity_x', neon: 'neon_runner',
  carbon: 'carbon_racer', hyper: 'hyper_boost', plasma: 'plasma_kicks', cosmic: 'cosmic_runner',
  galaxy: 'galaxy_high', quantum: 'quantum_sneakers',
};

/** Normalisation applied to every sneaker file (authors don't need exact scale/origin). */
export const SNEAKER_SPEC = {
  length: 0.31,     // metres heel→toe after auto-fit (the character's foot socket is sized for this)
  ankleU: 0.27,     // origin is placed under the ankle, 27% of the length from the heel
};

/** pet species → assets/pets/<file>.glb. Pets share species models; finishes (golden, neon…) are material variants. */
export const PET_FILES = {
  dog: 'dog', cat: 'cat', bunny: 'bunny', bird: 'pigeon', fox: 'fox', robodog: 'robot_dog',
  tiger: 'tiger', dragon: 'dragon', unicorn: 'unicorn', phoenix: 'phoenix', bear: 'bear', slime: 'slime',
};
export const PET_SPEC = { height: 0.72 };

/** Rigged player character. Clip names are matched case-insensitively against these aliases. */
export const CHARACTER = {
  file: 'characters/runner.glb',
  height: 1.8,
  // KayKit standard-rig clip names come first (Batch 1 runner, see ASSET_SPEC_BATCH1.md); exact matches win over partial ones.
  clips: {
    idle: ['idle', 'breathing idle', 'stand'],
    walk: ['walking_a', 'walk', 'walking'],
    run: ['running_a', 'run', 'running', 'jog'],
    sprint: ['sprint', 'fast run', 'run_fast'], // none on the KayKit rig → reuses run, sped up
    celebrate: ['cheer', 'celebrate', 'victory', 'dance', 'wave'],
    jump: ['jump_idle', 'jump', 'jumping', 'fall'],
    stumble: ['hit_a', 'stumble', 'hit', 'trip'],
  },
  // native ground speed (m/s) of each locomotion clip at timeScale 1 for a 1.8 m character
  clipSpeeds: { walk: 1.6, run: 3.9, sprint: 6.5 },
  // switch thresholds (m/s)
  walkUntil: 2.6,
  runUntil: 7.5,
  stepPhases: [0.0, 0.5],   // normalised clip times where a foot plants (footstep sounds)
  // Bone/mesh names are compared after normalisation: lower-case, every non-alphanumeric removed
  // (three.js strips '.' from glTF node names, so Blender's `Foot.L` arrives as `FootL`;
  // `foot_l`, `Foot.L`, `FootL` and `foot-l` all normalise to `footl`).
  footBones: {
    left: ['footl', 'leftfoot', 'lfoot', 'footleft', 'mixamorigleftfoot', 'deffootl'],
    right: ['footr', 'rightfoot', 'rfoot', 'footright', 'mixamorigrightfoot', 'deffootr'],
  },
  hipsBones: ['hips', 'mixamorighips', 'pelvis', 'root'],
  // the character's own shoes are hidden (substring match on the normalised mesh name); game sneakers attach to the feet.
  // `casualfeet` = Quaternius "Casual_Feet" (shoe-only mesh; the legs are a separate mesh and stay visible)
  hideMeshes: ['shoe', 'sneaker', 'footwear', 'casualfeet'],
  shoeScale: 1.12,
};

/** Lobby props → assets/props/<file>.glb, auto-fitted to these sizes (metres). */
export const PROPS = {
  tree:  { file: 'props/tree.glb',  fit: { height: 5.2 } },
  bench: { file: 'props/bench.glb', fit: { length: 2.6 } },
  lamp:  { file: 'props/lamp.glb',  fit: { height: 5.4 } },
  // sneaker-shop test corner (Kenney CC0), see Lobby.js "shop test corner"
  shop_counter: { file: 'props/shop_counter.glb', fit: { length: 2.5 } },
  shop_bench:   { file: 'props/shop_bench.glb',   fit: { length: 1.25 } },
  shop_plant:   { file: 'props/shop_plant.glb',   fit: { height: 1.4 } },
  shop_lamp:    { file: 'props/shop_lamp.glb',    fit: { height: 2.3 } },
};

/** Future slots (documented now, wired in later migration steps). */
export const FUTURE_SLOTS = [
  'environment/sneaker_shop.glb', 'environment/pet_hatchery.glb', 'environment/run_portal.glb',
  'environment/building_a.glb', 'environment/building_b.glb', 'environment/building_c.glb',
  // Batch 1 sneaker-shop display set (ASSET_SPEC_BATCH1.md); placement code is wired when the files arrive
  'props/shop_wall_shelf.glb', 'props/shop_slatwall.glb', 'props/shop_pedestal_round.glb', 'props/shop_tryon_bench.glb',
  'props/shop_counter.glb', 'props/shop_shoebox.glb',
  'props/planter.glb', 'props/bollard.glb',
  'props/neon_sign.glb', 'props/track_hurdle.glb', 'props/traffic_barrier.glb', 'props/egg.glb',
];

/** Per-file tuning without re-exporting (rotate a model that faces the wrong way, nudge sockets…). */
export const ASSET_OVERRIDES = {
  // Kenney Cube Pets are chunky; slightly smaller than the 0.72 m fit so they sit well beside the chibi runner
  // Quaternius chibi runner: short legs cover less ground per cycle, so its clips are slower than the defaults
  // (measured planted-foot slide), faster playback is allowed at sprint speeds, and the sneaker sockets sit 1 cm
  // higher so planted soles rest on the ground. Animation playback only — movement speeds are unchanged.
  'characters/runner.glb': { clipSpeeds: { walk: 0.95, run: 1.5 }, maxTimeScale: 5, socketOffset: [0, 0.01, 0] },
  'pets/dog.glb': { scale: 0.8 },
  'pets/cat.glb': { scale: 0.8 },
  // 'sneakers/starter_canvas.glb': { rotateY: 90 },
};
